json_data={
    "response":
        {
            "header":
                {
                    "resultCode":"0000",
                    "resultMsg":"OK"
                },
            "body":
                {
                    "items":
                        {
                            "item":
                                [
                                    {
                                        "baseDate":20180501,
                                        "baseTime":1030,
                                        "category":"LGT",
                                        "fcstDate":20180501,
                                        "fcstTime":1100,
                                        "fcstValue":0,
                                        "nx":89,
                                        "ny":91
                                    },
                                    {
                                        "baseDate":20180501,
                                        "baseTime":1030,
                                        "category":"LGT",
                                        "fcstDate":20180501,
                                        "fcstTime":1200,
                                        "fcstValue":0,
                                        "nx":89,
                                        "ny":91
                                    },
                                    {
                                        "baseDate":20180501,
                                        "baseTime":1030,
                                        "category":"PTY",
                                        "fcstDate":20180501,
                                        "fcstTime":1100,
                                        "fcstValue":0,
                                        "nx":89,
                                        "ny":91
                                    },
                                    {
                                        "baseDate":20180501,
                                        "baseTime":1030,
                                        "category":"PTY",
                                        "fcstDate":20180501,
                                        "fcstTime":1200,
                                        "fcstValue":0,
                                        "nx":89,
                                        "ny":91
                                    },
                                    {
                                        "baseDate":20180501,
                                        "baseTime":1030,
                                        "category":"RN1",
                                        "fcstDate":20180501,
                                        "fcstTime":1100,
                                        "fcstValue":0,
                                        "nx":89,
                                        "ny":91
                                    },
                                    {
                                        "baseDate":20180501,
                                        "baseTime":1030,
                                        "category":"RN1",
                                        "fcstDate":20180501,
                                        "fcstTime":1200,
                                        "fcstValue":0,
                                        "nx":89,
                                        "ny":91
                                    },
                                    {
                                        "baseDate":20180501,
                                        "baseTime":1030,
                                        "category":"SKY",
                                        "fcstDate":20180501,
                                        "fcstTime":1100,
                                        "fcstValue":3,
                                        "nx":89,
                                        "ny":91
                                    },
                                    {
                                        "baseDate":20180501,
                                        "baseTime":1030,
                                        "category":"SKY",
                                        "fcstDate":20180501,
                                        "fcstTime":1200,
                                        "fcstValue":3,
                                        "nx":89,
                                        "ny":91
                                    },
                                    {
                                        "baseDate":20180501,
                                        "baseTime":1030,
                                        "category":"T1H",
                                        "fcstDate":20180501,
                                        "fcstTime":1100,
                                        "fcstValue":23,
                                        "nx":89,
                                        "ny":91
                                    },
                                    {
                                        "baseDate":20180501,
                                        "baseTime":1030,
                                        "category":"T1H",
                                        "fcstDate":20180501,
                                        "fcstTime":1200,
                                        "fcstValue":24,
                                        "nx":89,
                                        "ny":91
                                    },
                                    {
                                        "baseDate":20180501,
                                        "baseTime":1030,
                                        "category":"REH",
                                        "fcstDate":20180501,
                                        "fcstTime":1100,
                                        "fcstValue":55,
                                        "nx":89,
                                        "ny":91
                                    },
                                    {
                                        "baseDate":20180501,
                                        "baseTime":1030,
                                        "category":"REH",
                                        "fcstDate":20180501,
                                        "fcstTime":1200,
                                        "fcstValue":50,
                                        "nx":89,
                                        "ny":91
                                    },
                                    {
                                        "baseDate":20180501,
                                        "baseTime":1030,
                                        "category":"UUU",
                                        "fcstDate":20180501,
                                        "fcstTime":1100,
                                        "fcstValue":-0.6,
                                        "nx":89,
                                        "ny":91
                                    },
                                    {
                                        "baseDate":20180501,
                                        "baseTime":1030,
                                        "category":"UUU",
                                        "fcstDate":20180501,
                                        "fcstTime":1200,
                                        "fcstValue":0.4,
                                        "nx":89,
                                        "ny":91
                                    },
                                    {
                                        "baseDate":20180501,
                                        "baseTime":1030,
                                        "category":"VVV",
                                        "fcstDate":20180501,
                                        "fcstTime":1100,
                                        "fcstValue":0.9,
                                        "nx":89,
                                        "ny":91
                                    },
                                    {
                                        "baseDate":20180501,
                                        "baseTime":1030,
                                        "category":"VVV",
                                        "fcstDate":20180501,
                                        "fcstTime":1200,
                                        "fcstValue":1.6,
                                        "nx":89,
                                        "ny":91
                                    },
                                    {
                                        "baseDate":20180501,
                                        "baseTime":1030,
                                        "category":"VEC",
                                        "fcstDate":20180501,
                                        "fcstTime":1100,
                                        "fcstValue":143,
                                        "nx":89,
                                        "ny":91
                                    },
                                    {
                                        "baseDate":20180501,
                                        "baseTime":1030,
                                        "category":"VEC",
                                        "fcstDate":20180501,
                                        "fcstTime":1200,
                                        "fcstValue":194,
                                        "nx":89,
                                        "ny":91
                                    },
                                    {
                                        "baseDate":20180501,
                                        "baseTime":1030,
                                        "category":"WSD",
                                        "fcstDate":20180501,
                                        "fcstTime":1100,
                                        "fcstValue":1.1,
                                        "nx":89,
                                        "ny":91
                                    },
                                    {
                                        "baseDate":20180501,
                                        "baseTime":1030,
                                        "category":"WSD",
                                        "fcstDate":20180501,
                                        "fcstTime":1200,
                                        "fcstValue":1.6,
                                        "nx":89,
                                        "ny":91
                                    }
                                ]
                        },
                    "numOfRows":30,
                    "pageNo":1,
                    "totalCount":20
                }
        }
}

item = json_data["response"]["body"]["items"]["item"][5]["fcstValue"]
print(item)


# print(json_data.get('RN1'))


# print(json_data["response"])